### ISSUE TITLE
Selecting filters produce a lot of pemding requests

### ISSUE THREAD

**Issue by dyanakiev** [typesense/showcase-songs-search#3]
## Description

When i select random filters fastly a lot of requests are spammed in the network tab and they are pending so i need to wait all of them to finish to see the end result. Probably some type of wait timer should be implement lets say 1 second before a request is sent.

## Steps to reproduce

Select multiple filters, watch browser network tab.

## Expected Behavior

Send requests some time after user finish selecting filters.

## Actual Behavior

Spamming requests on every click leading to a lot of pending requests and data not loading until all finished.

## Metadata

**Typsense Version**: songs-search.typesense.org

**OS**: songs-search.typesense.org

**Comment by jasonbosco** [comment]
@dyanakiev Here's why this happens: https://github.com/typesense/typesense-instantsearch-adapter/issues/10#issuecomment-761281888

Good news is that we're addressing this in v0.19. I'll be updating this demo shortly to use v0.19 and that should address the multiple requests.

**Comment by jasonbosco** [comment]
Just published v0.19.0 of Typesense Server which supports multi_search. I've also published v1.0.0 of the InstantSearch Typesense adapter which takes advantage of this feature, and updated the songs search demo to use this latest version.

You should now see only one multi_search request being made regardless of the number of filter widgets used.
