### ISSUE TITLE
Not really an issue but really nice to have comments in the code which tells us how to make results clickable

### ISSUE THREAD

**Issue by lindamacdonald** [typesense/showcase-songs-search#4]
## Description I would love it if the code had some sort of comment inbuilt to show us how to make the results clickable if possible?

**Comment by jasonbosco** [comment]
Hi @lindamacdonald, here's where I've made the artist names clickable: 

https://github.com/typesense/showcase-songs-search/blob/e6aeb0bc744e2623bc28ec2a45760da0774f3065/src/app.js#L230

https://github.com/typesense/showcase-songs-search/blob/e6aeb0bc744e2623bc28ec2a45760da0774f3065/src/app.js#L388-L391

https://github.com/typesense/showcase-songs-search/blob/e6aeb0bc744e2623bc28ec2a45760da0774f3065/src/app.js#L403-L404

Does that help?

**Comment by lindamacdonald** [comment]
Sooooory Jason. I thought i deleted this request i noticed it straight
after posting 🤐🙂

lør. 3. jul. 2021, 20:45 skrev Jason Bosco ***@***.***>:

**Comment by jasonbosco** [comment]
No worries!
