### ISSUE TITLE
How is the musicbrainz data collated?

### ISSUE THREAD

**Issue by Tails** [typesense/showcase-songs-search#9]
MusicBrainz provides Musicbrainz data by Postgres server, or by [JSON dumps](https://data.metabrainz.org/pub/musicbrainz/data/json-dumps/20240508-001002/). I'm assuming the example data here is collated from the JSON dumps, but how is the data file for the single schema format generated?

**Comment by jasonbosco** [comment]
Here's the indexing script: https://github.com/typesense/showcase-songs-search/blob/master/scripts/indexer/index.js

**Comment by jasonbosco** [comment]
I remember it being a single JSON file dump from MusicBrainz... May be the release groups JSON dump?

**Comment by Tails** [comment]
Ah ok, so the file is not a unified amalgation. Thanks!
